from pkgsettings import Settings

settings = Settings()

settings.configure(
    SERVICE_KSTREAMS_KAFKA_CONFIG_BOOTSTRAP_SERVERS=["localhost:9092"],
    SERVICE_KSTREAMS_KAFKA_CONFIG_SECURITY_PROTOCOL="PLAINTEXT",
    SERVICE_KSTREAMS_KAFKA_SSL_CERT_DATA=None,
    SERVICE_KSTREAMS_KAFKA_SSL_KEY_DATA=None,
    SERVICE_KSTREAMS_KAFKA_SSL_CABUNDLE_DATA=None,
    SERVICE_KSTREAMS_KAFKA_SSL_CONTEXT=None,
    SERVICE_KSTREAMS_KAFKA_TOPIC_PREFIX="dev--",
)
