#!/bin/bash -e

export PREFIX=""
if [ -d '.venv' ] ; then
    export PREFIX=".venv/bin/"
fi

${PREFIX}pytest -x --cov-report term-missing --cov-report=xml:coverage.xml --cov=kstreams ${1-"./tests"} $2
${PREFIX}ruff check kstreams tests
${PREFIX}ruff format --check kstreams tests examples
${PREFIX}mypy kstreams/ tests/
