name: Bump version

on:
  push:
    branches:
      - master

jobs:
  bench_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
    - name: Check out
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Set Cache
      uses: actions/cache@v4
      id: cache  # name for referring later
      with:
        path: .venv/
        # The cache key depends on poetry.lock
        key: ${{ runner.os }}-cache-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-cache-
          ${{ runner.os }}-

    - name: Install Dependencies
      # if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install -U pip poetry
        poetry --version
        poetry config --local virtualenvs.in-project true
        poetry install
    - name: Benchmark code
      run: |
        ./scripts/bench-current
    - name: Commit benchmark
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .benchmarks/
        git commit -m "bench: bench: add benchmark current release"
        git push origin master
